# Generated by Django 4.2.7 on 2024-01-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(default='DefaultCategory', max_length=30),
            preserve_default=False,
        ),
    ]
